[package]
description = "Function transformations for functional programming"
name = "funcy"
version = "0.0.1"
authors = ["Inityx"]
license = "LGPL-2.1-or-later"
edition = "2018"
repository = "https://github.com/Inityx/funcy"

[dependencies]
